/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio_evaluable_3.h"



int init()
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *innit_1_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, INNIT_PROG, INNIT_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = innit_1((void*)&innit_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    return result_1;
#ifndef	DEBUG
#endif	 /* DEBUG */
}



int set_value(int key, char* val_1, int n_elem, double* vector)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct mensaje  set_value_2_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, SET_VALUE_PROG, SET_VALUE_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    set_value_2_arg.key = key;
    set_value_2_arg.val_1 = (char*)malloc(sizeof (val_1)* sizeof(char));
    strcpy(set_value_2_arg.val_1, val_1);
    set_value_2_arg.vector.vector_val = (double*)malloc(n_elem * sizeof(double));
    set_value_2_arg.vector.vector_len = n_elem;
    for (int i = 0; i < set_value_2_arg.vector.vector_len; i++) {
        set_value_2_arg.vector.vector_val[i] = vector[i];
    }

    retval_1 = set_value_2(&set_value_2_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
    }
    return result_1;

#ifndef	DEBUG
#endif	 /* DEBUG */
}



int get_value(int key, char *value1, int *N_value2, double *V_value2)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct mensaje result_1;
	int  get_value_3_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, GET_VALUE_PROG, GET_VALUE_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    get_value_3_arg = key;
    result_1.val_1 = (char *)malloc(256 * sizeof(char));
    result_1.vector.vector_val = (double *)malloc(32 * sizeof(double));
    retval_1 = get_value_3(&get_value_3_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
    }

    if(result_1.key != -1){
        key =  get_value_3_arg;
        strcpy(value1, result_1.val_1);
        N_value2 = (int*)&result_1.vector.vector_len;
        for(int i = 0; i < result_1.vector.vector_len; i++){
            V_value2[i] = result_1.vector.vector_val[i];
        }
    return 0;
    }
    return -1;

#ifndef	DEBUG
#endif	 /* DEBUG */
}



int modify_value(int key, char* val_1, int n_elem, double* vector)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct mensaje  modify_value_4_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    modify_value_4_arg.key = key;
    modify_value_4_arg.val_1 = (char*)malloc(sizeof (val_1)* sizeof(char));
    strcpy(modify_value_4_arg.val_1, val_1);
    modify_value_4_arg.vector.vector_val = (double*)malloc(n_elem * sizeof(double));
    modify_value_4_arg.vector.vector_len = n_elem;
    for (int i = 0; i < modify_value_4_arg.vector.vector_len; i++) {
        modify_value_4_arg.vector.vector_val[i] = vector[i];
    }

    retval_1 = modify_value_4(&modify_value_4_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        return -1;
        clnt_destroy (clnt);
    }
    return result_1;
#ifndef	DEBUG
#endif	 /* DEBUG */
}



int delete_key(int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int  delete_key_5_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, DELETE_KEY_PROG, DELETE_KEY_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


    delete_key_5_arg = key;
	retval_1 = delete_key_5(&delete_key_5_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    return result_1;

#ifndef	DEBUG

#endif	 /* DEBUG */
}



int exist(int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int  exist_6_arg;

#ifndef	DEBUG
    char *host = getenv("IP_TUPLAS");
    if (host == NULL) {
        fprintf(stderr, "Error: La variable de entorno 'IP_TUPLAS' no está definida.\n");
        exit(1);
    }
	clnt = clnt_create (host, EXIST_PROG, EXIST_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    exist_6_arg = key;
	retval_1 = exist_6(&exist_6_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    return result_1;
#ifndef	DEBUG

#endif	 /* DEBUG */
}

