/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _EJERCICIO_EVALUABLE_3_H_RPCGEN
#define _EJERCICIO_EVALUABLE_3_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct mensaje {
	int key;
	char *val_1;
	struct {
		u_int vector_len;
		double *vector_val;
	} vector;
};
typedef struct mensaje mensaje;

#define INNIT_PROG 0x20000001
#define INNIT_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define INNIT 1
extern  enum clnt_stat innit_1(void *, int *, CLIENT *);
extern  bool_t innit_1_svc(void *, int *, struct svc_req *);
extern int innit_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INNIT 1
extern  enum clnt_stat innit_1();
extern  bool_t innit_1_svc();
extern int innit_prog_1_freeresult ();
#endif /* K&R C */

#define SET_VALUE_PROG 0x20000002
#define SET_VALUE_VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define SET_VALUE 1
extern  enum clnt_stat set_value_2(struct mensaje *, int *, CLIENT *);
extern  bool_t set_value_2_svc(struct mensaje *, int *, struct svc_req *);
extern int set_value_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SET_VALUE 1
extern  enum clnt_stat set_value_2();
extern  bool_t set_value_2_svc();
extern int set_value_prog_2_freeresult ();
#endif /* K&R C */

#define GET_VALUE_PROG 0x20000003
#define GET_VALUE_VERSION 3

#if defined(__STDC__) || defined(__cplusplus)
#define GET_VALUE 1
extern  enum clnt_stat get_value_3(int *, struct mensaje *, CLIENT *);
extern  bool_t get_value_3_svc(int *, struct mensaje *, struct svc_req *);
extern int get_value_prog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_VALUE 1
extern  enum clnt_stat get_value_3();
extern  bool_t get_value_3_svc();
extern int get_value_prog_3_freeresult ();
#endif /* K&R C */

#define MODIFY_VALUE_PROG 0x20000004
#define MODIFY_VALUE_VERSION 4

#if defined(__STDC__) || defined(__cplusplus)
#define MODIFY_VALUE 1
extern  enum clnt_stat modify_value_4(struct mensaje *, int *, CLIENT *);
extern  bool_t modify_value_4_svc(struct mensaje *, int *, struct svc_req *);
extern int modify_value_prog_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MODIFY_VALUE 1
extern  enum clnt_stat modify_value_4();
extern  bool_t modify_value_4_svc();
extern int modify_value_prog_4_freeresult ();
#endif /* K&R C */

#define DELETE_KEY_PROG 0x20000005
#define DELETE_KEY_VERSION 5

#if defined(__STDC__) || defined(__cplusplus)
#define DELETE_KEY 1
extern  enum clnt_stat delete_key_5(int *, int *, CLIENT *);
extern  bool_t delete_key_5_svc(int *, int *, struct svc_req *);
extern int delete_key_prog_5_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DELETE_KEY 1
extern  enum clnt_stat delete_key_5();
extern  bool_t delete_key_5_svc();
extern int delete_key_prog_5_freeresult ();
#endif /* K&R C */

#define EXIST_PROG 0x20000006
#define EXIST_VERSION 6

#if defined(__STDC__) || defined(__cplusplus)
#define EXIST 1
extern  enum clnt_stat exist_6(int *, int *, CLIENT *);
extern  bool_t exist_6_svc(int *, int *, struct svc_req *);
extern int exist_prog_6_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXIST 1
extern  enum clnt_stat exist_6();
extern  bool_t exist_6_svc();
extern int exist_prog_6_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mensaje (XDR *, mensaje*);

#else /* K&R C */
extern bool_t xdr_mensaje ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_EJERCICIO_EVALUABLE_3_H_RPCGEN */
