/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio_evaluable_3.h"


void
innit(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char *innit_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INNIT_PROG, INNIT_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = innit_1((void*)&innit_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    printf("Resultado de la operación: %d\n", result_1);
#ifndef	DEBUG
#endif	 /* DEBUG */
}


void
set_value(char *host, int key, char* val_1, int n_elem, double* vector)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct mensaje  set_value_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SET_VALUE_PROG, SET_VALUE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    set_value_2_arg.key = key;
    set_value_2_arg.val_1 = (char*)malloc(sizeof (val_1)* sizeof(char));
    strcpy(set_value_2_arg.val_1, val_1);
    set_value_2_arg.vector.vector_val = (double*)malloc(n_elem * sizeof(double));
    set_value_2_arg.vector.vector_len = n_elem;
    for (int i = 0; i < set_value_2_arg.vector.vector_len; i++) {
        set_value_2_arg.vector.vector_val[i] = vector[i];
    }

    retval_1 = set_value_2(&set_value_2_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
    }

#ifndef	DEBUG
#endif	 /* DEBUG */
}


void
get_value(char *host, int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct mensaje result_1;
	int  get_value_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GET_VALUE_PROG, GET_VALUE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    get_value_3_arg = key;
    result_1.val_1 = (char *)malloc(256 * sizeof(char));
    result_1.vector.vector_val = (double *)malloc(32 * sizeof(double));
    retval_1 = get_value_3(&get_value_3_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
    }
    if(result_1.key != -1){
    printf("key = %d\n", get_value_3_arg);
    printf("val_1 = %s\n", result_1.val_1);
    printf("n_elem = %d\n", result_1.vector.vector_len);
    for(int i = 0; i < result_1.vector.vector_len; i++){
        printf("vector[%d] = %lf\n", i, result_1.vector.vector_val[i]);
    }}
    printf("resultado = %d\n", result_1.key);

#ifndef	DEBUG
#endif	 /* DEBUG */
}


void
modify_value(char *host, int key, char* val_1, int n_elem, double* vector)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct mensaje  modify_value_4_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    modify_value_4_arg.key = key;
    modify_value_4_arg.val_1 = (char*)malloc(sizeof (val_1)* sizeof(char));
    strcpy(modify_value_4_arg.val_1, val_1);
    modify_value_4_arg.vector.vector_val = (double*)malloc(n_elem * sizeof(double));
    modify_value_4_arg.vector.vector_len = n_elem;
    for (int i = 0; i < modify_value_4_arg.vector.vector_len; i++) {
        modify_value_4_arg.vector.vector_val[i] = vector[i];
    }

    retval_1 = modify_value_4(&modify_value_4_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
    }
    printf("Resultado = %d\n", result_1);

#ifndef	DEBUG
#endif	 /* DEBUG */
}


void
delete_key(char *host, int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int  delete_key_5_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DELETE_KEY_PROG, DELETE_KEY_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


    delete_key_5_arg = key;
	retval_1 = delete_key_5(&delete_key_5_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    printf("Resultado = %d\n",result_1);
#ifndef	DEBUG

#endif	 /* DEBUG */
}


void
exist(char *host, int key)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	int  exist_6_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, EXIST_PROG, EXIST_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    exist_6_arg = key;
	retval_1 = exist_6(&exist_6_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
        clnt_destroy (clnt);
	}
    printf("Resultado = %d\n", result_1);
#ifndef	DEBUG

#endif	 /* DEBUG */
}

