/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ejercicio_evaluable_3.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
innit_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	union {
		int innit_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INNIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))innit_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!innit_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
set_value_prog_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct mensaje set_value_2_arg;
	} argument;
	union {
		int set_value_2_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SET_VALUE:
		_xdr_argument = (xdrproc_t) xdr_mensaje;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))set_value_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!set_value_prog_2_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
get_value_prog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int get_value_3_arg;
	} argument;
	union {
		struct mensaje get_value_3_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_VALUE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_mensaje;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_value_3_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!get_value_prog_3_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
modify_value_prog_4(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct mensaje modify_value_4_arg;
	} argument;
	union {
		int modify_value_4_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MODIFY_VALUE:
		_xdr_argument = (xdrproc_t) xdr_mensaje;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))modify_value_4_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!modify_value_prog_4_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
delete_key_prog_5(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int delete_key_5_arg;
	} argument;
	union {
		int delete_key_5_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DELETE_KEY:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))delete_key_5_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!delete_key_prog_5_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

static void
exist_prog_6(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int exist_6_arg;
	} argument;
	union {
		int exist_6_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case EXIST:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))exist_6_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!exist_prog_6_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (INNIT_PROG, INNIT_VERSION);
	pmap_unset (SET_VALUE_PROG, SET_VALUE_VERSION);
	pmap_unset (GET_VALUE_PROG, GET_VALUE_VERSION);
	pmap_unset (MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION);
	pmap_unset (DELETE_KEY_PROG, DELETE_KEY_VERSION);
	pmap_unset (EXIST_PROG, EXIST_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, INNIT_PROG, INNIT_VERSION, innit_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INNIT_PROG, INNIT_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, SET_VALUE_PROG, SET_VALUE_VERSION, set_value_prog_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SET_VALUE_PROG, SET_VALUE_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, GET_VALUE_PROG, GET_VALUE_VERSION, get_value_prog_3, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GET_VALUE_PROG, GET_VALUE_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, modify_value_prog_4, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, DELETE_KEY_PROG, DELETE_KEY_VERSION, delete_key_prog_5, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DELETE_KEY_PROG, DELETE_KEY_VERSION, udp).");
		exit(1);
	}
	if (!svc_register(transp, EXIST_PROG, EXIST_VERSION, exist_prog_6, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EXIST_PROG, EXIST_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, INNIT_PROG, INNIT_VERSION, innit_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INNIT_PROG, INNIT_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SET_VALUE_PROG, SET_VALUE_VERSION, set_value_prog_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SET_VALUE_PROG, SET_VALUE_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GET_VALUE_PROG, GET_VALUE_VERSION, get_value_prog_3, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GET_VALUE_PROG, GET_VALUE_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, modify_value_prog_4, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MODIFY_VALUE_PROG, MODIFY_VALUE_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DELETE_KEY_PROG, DELETE_KEY_VERSION, delete_key_prog_5, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DELETE_KEY_PROG, DELETE_KEY_VERSION, tcp).");
		exit(1);
	}
	if (!svc_register(transp, EXIST_PROG, EXIST_VERSION, exist_prog_6, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (EXIST_PROG, EXIST_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
