CC = gcc
CFLAGS = -Wall -g -I/usr/include/tirpc
LDLIBS += -lnsl -lpthread -ldl -ltirpc

# Lista de archivos fuente
SERVER_SRCS = ejercicio_evaluable_3_server.c ejercicio_evaluable_3_svc.c ejercicio_evaluable_3_xdr.c
CLIENT_SRCS = ejercicio_evaluable_3_client.c ejercicio_evaluable_3_client.h ejercicio_evaluable_3_clnt.c cliente.c

# Lista de objetos a generar
SERVER_OBJS = $(SERVER_SRCS:.c=.o)
CLIENT_OBJS = $(CLIENT_SRCS:.c=.o)

# Nombre del ejecutable del servidor
SERVER_EXEC = servidor

# Nombre de la librería dinámica del cliente
CLIENT_LIB = libejercicio_evaluable_3_client.so

# Nombre del ejecutable del cliente
CLIENT_EXEC = cliente

all: $(SERVER_EXEC) $(CLIENT_LIB) $(CLIENT_EXEC)

# Compilar el ejecutable del servidor
$(SERVER_EXEC): $(SERVER_OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS)

# Compilar el archivo del cliente
ejercicio_evaluable_3_client.o: ejercicio_evaluable_3_client.c ejercicio_evaluable_3_client.h ejercicio_evaluable_3_clnt.c
	$(CC) $(CFLAGS) -fPIC -c -o $@ $<

# Regla genérica para compilar archivos fuente a objetos
%.o: %.c
	$(CC) $(CFLAGS) -fPIC -c -o $@ $<

# Compilar la librería dinámica del cliente
$(CLIENT_LIB): $(CLIENT_OBJS)
	$(CC) $(CFLAGS) -shared -o $@ $^ $(LDLIBS)

# Compilar el ejecutable del cliente
$(CLIENT_EXEC): cliente.o ejercicio_evaluable_3_xdr.o
	$(CC) $(CFLAGS) -o $@ $^ -L$(LIB_LOCATION) -lejercicio_evaluable_3_client $(LDLIBS) -Wl,-rpath=$(LIB_LOCATION)

clean:
	rm -f $(SERVER_EXEC) $(CLIENT_LIB) $(CLIENT_EXEC) $(SERVER_OBJS) $(CLIENT_OBJS)
