/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <stdio.h>  // Agregado para imprimir mensajes de depuración
#include <memory.h> // for memset
#include "rpc_conexion.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *imprimir_operacion_usuario_1(usuario_operacion *argp, CLIENT *clnt)
{   
    printf("Entrando a imprimir_operacion_usuario_1\n");

    // Agregamos más mensajes de depuración para entender el flujo del programa
    printf("Antes de llamar a clnt_call\n");
    
    static char clnt_res;
    memset((char *)&clnt_res, 0, sizeof(clnt_res));

    // Llamamos a clnt_call y almacenamos el resultado
    enum clnt_stat call_status = clnt_call(clnt, imprimir_operacion_usuario,
        (xdrproc_t) xdr_usuario_operacion, (caddr_t) argp,
        (xdrproc_t) xdr_void, (caddr_t) &clnt_res,
        TIMEOUT);

    printf("Después de llamar a clnt_call\n");

    // Verificamos el estado de la llamada
    if (call_status != RPC_SUCCESS) {
        fprintf(stderr, "Error al llamar a clnt_call: %s\n", clnt_sperrno(call_status));
        return NULL;
    }

    return ((void *)&clnt_res);
}
