/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_CONEXION_H_RPCGEN
#define _RPC_CONEXION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct usuario_operacion {
	char *usuario;
	char *operacion;
	char *fecha;
	char *file_name;
};
typedef struct usuario_operacion usuario_operacion;

#define OPERACIONES_PROG 0x31230000
#define OPERACIONES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define imprimir_operacion_usuario 1
extern  void * imprimir_operacion_usuario_1(usuario_operacion *, CLIENT *);
extern  void * imprimir_operacion_usuario_1_svc(usuario_operacion *, struct svc_req *);
extern int operaciones_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define imprimir_operacion_usuario 1
extern  void * imprimir_operacion_usuario_1();
extern  void * imprimir_operacion_usuario_1_svc();
extern int operaciones_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usuario_operacion (XDR *, usuario_operacion*);

#else /* K&R C */
extern bool_t xdr_usuario_operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_CONEXION_H_RPCGEN */
